### ISSUE TITLE
A BUG 

### ISSUE THREAD

**Issue by jQsW** [Sfiguz7/TranscEndence#20]
Block Info:
  World: world_the_end
  X: -282
  Y: 1
  Z: -7
  Material: WHITE_CONCRETE
  Block Data: org.bukkit.craftbukkit.v1_18_R1.block.data.CraftBlockData
  State: org.bukkit.craftbukkit.v1_18_R1.block.CraftBlockState

Ticker-Info:
  Type: Synchronized

Slimefun Data:
  ID: ZOT_OVERLOADER
  Inventory: true
  Data: {"energy-charge":"2048","id":"ZOT_OVERLOADER"}

Stacktrace:

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at [sf附属末地科技]TranscEndence-Build 2 zh-CN(baoad) (git ae7bd81).jar//me.sfiguz7.transcendence.implementation.items.machines.ZotOverloader$1.tick(ZotOverloader.java:177)
	at [粘液]Slimefun-v4.9-canary-8afab5b.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189)
	at [粘液]Slimefun-v4.9-canary-8afab5b.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tickLocation$2(TickerTask.java:170)
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1578)
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:519)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1501)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1285)
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Alessio-Colombo** [comment]
You do not use the official TranscEndence build so I cannot help you. Use the official version
