### ISSUE TITLE
Plugin has issue with Metrics and disables itself on boot.

### ISSUE THREAD

**Issue by Mrs-Feathers** [Sfiguz7/TranscEndence#4]
## Description (Required)
It does not enable on boot for my server.

## Steps to reproduce the Issue (Required)
1. install plugin
2. boot up server
3. notice it doesn't appear in slimefun and the commands don't work.

## Expected behavior (Required)
i expected it to show up and work

## Server Log / Error Report
```
[20:35:21] [Server thread/ERROR]: Error occurred while enabling TranscEndence vDEV - 8 (git 45d671f3) (Is it up to date?)
java.lang.NoSuchMethodError: me.mrCookieSlime.bstats.bukkit.Metrics.<init>(Lorg/bukkit/plugin/Plugin;I)V
	at me.sfiguz7.transcendence.TranscEndence.onEnable(TranscEndence.java:58) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Spigot-2f5d615-d07a78b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [server.jar:git-Spigot-2f5d615-d07a78b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [server.jar:git-Spigot-2f5d615-d07a78b]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [server.jar:git-Spigot-2f5d615-d07a78b]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [server.jar:git-Spigot-2f5d615-d07a78b]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [server.jar:git-Spigot-2f5d615-d07a78b]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [server.jar:git-Spigot-2f5d615-d07a78b]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [server.jar:git-Spigot-2f5d615-d07a78b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

## Environment (Required)
```
[08:53:10] [Server thread/INFO]: CraftBukkit v1_15_R1
[08:53:10] [Server thread/INFO]: CS-CoreLib vDEV - 79 (git ec5b4c24)
[08:53:10] [Server thread/INFO]: Slimefun vDEV - 513 (git 23c2ab0f)
[08:53:10] [Server thread/INFO]: Installed Addons (19)
[08:53:10] [Server thread/INFO]:  ExtraTools vDEV - 14 (git a330a3dd)
[08:53:10] [Server thread/INFO]:  SlimefunOreChunks vDEV - 8 (git 41e31ffc)
[08:53:10] [Server thread/INFO]:  HotbarPets vDEV - 27 (git 975a8997)
[08:53:10] [Server thread/INFO]:  SlimefunOres v1.0.0
[08:53:10] [Server thread/INFO]:  SlimefunMothCraft v0.1.4
[08:53:10] [Server thread/INFO]:  ExtraGear vDEV - 9 (git e851d81d)
[08:53:10] [Server thread/INFO]:  SlimefunLuckyBlocks vDEV - 19 (git 9dbab303)
[08:53:10] [Server thread/INFO]:  ExoticGarden vDEV - 46 (git fe5109fe)
[08:53:10] [Server thread/INFO]:  Barrels vDEV - 11 (git abecba9c)
[08:53:10] [Server thread/INFO]:  ClayTech v1.2.0-pre3
[08:53:10] [Server thread/INFO]:  ElectricSpawners vDEV - 12 (git 4ae47f83)
[08:53:10] [Server thread/INFO]:  LiteXpansion vDEV - 32 (git 8d9b202b)
[08:53:10] [Server thread/INFO]:  WhatIsThis v2.9
[08:53:10] [Server thread/INFO]:  MobCapturer vDEV - 7 (git b61d3fbf)
[08:53:10] [Server thread/INFO]:  SlimyTreeTaps vDEV - 11 (git b64db511)
[08:53:10] [Server thread/INFO]:  PrivateStorage vDEV - 11 (git b064863b)
[08:53:10] [Server thread/INFO]:  ColoredEnderChests vDEV - 12 (git 8dbdc909)
[08:53:10] [Server thread/INFO]:  TranscEndence vDEV - 8 (git 45d671f3)
```

**Comment by Alessio-Colombo** [comment]
Does ExtraTools load properly? They should use the same exact method :/ I'll try reproducing it locally in the meantime

**Comment by Alessio-Colombo** [comment]
I cannot reproduce it on my end. I do use CSCoreLib #85 which is latest at this time but that should not be an issue, as I said the method used by TranscEndence is the exact same as the one used by ExtraTools. I would give updating CSCL a shot

**Comment by Mrs-Feathers** [comment]
Yes. Extra tools does work

**Comment by Alessio-Colombo** [comment]
Updating CSCL would've in fact worked. I have nonetheless changed the import so it should now be fine even if you use the outdated version.

**Comment by Mrs-Feathers** [comment]
wasn't able to update it due to some conflictions... but can confirm transcendence works now.
