### ISSUE TITLE
Auto update? 

### ISSUE THREAD

**Issue by bobhenl** [Sfiguz7/TranscEndence#8]
## Description (Required)
Hello, could you add auto update? I'm still on ver 14 and there is already 17 out, so it's probably isn't implemented yet?

## Steps to reproduce the Issue (Required)
Install older version of plugin and you see if it updates.

## Expected behavior (Required)
Should update automatically.

## Server Log / Error Report
I found this in log so I discovered that I have old version....
```
[13:17:09] [Server thread/ERROR]: Error occurred while enabling TranscEndence vDEV - 14 (git 0017e2cb) (Is it up to date?)
java.lang.NoSuchMethodError: 'void me.mrCookieSlime.Slimefun.api.Slimefun.registerResearch(me.mrCookieSlime.Slimefun.Objects.Research, org.bukkit.inventory.ItemStack[])'
	at me.sfiguz7.transcendence.TranscEndence.onEnable(TranscEndence.java:100) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-101]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

## Environment (Required)

 - Minecraft Version: 1.16.1
 - CS-CoreLib Version: 88
 - Slimefun Version: 588
 - Plugin Version:  17 (but will update to 18 aswell)

**Comment by Alessio-Colombo** [comment]
Same spiel as ExtraTools issue #6, auto update fixed 2 days ago :)
